// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jhdmQ6bfG1eeKjRqZ2vC0uY1QqbbcNA',
    appId: '1:123249181420:web:43c97fc6bb723ca7255bc9',
    messagingSenderId: '123249181420',
    projectId: 'flutterai-d8cd5',
    authDomain: 'flutterai-d8cd5.firebaseapp.com',
    storageBucket: 'flutterai-d8cd5.firebasestorage.app',
    measurementId: 'G-5E4TM1J6FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBcz-ckTpQfj_5Ur1Ie-u83ejG0wOkLIY',
    appId: '1:123249181420:android:660381e7525b8666255bc9',
    messagingSenderId: '123249181420',
    projectId: 'flutterai-d8cd5',
    storageBucket: 'flutterai-d8cd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNNtF3Z_J3eRKUA2eZMTqdJyW2Wwtc_c',
    appId: '1:123249181420:ios:3918557103fb1158255bc9',
    messagingSenderId: '123249181420',
    projectId: 'flutterai-d8cd5',
    storageBucket: 'flutterai-d8cd5.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeNNtF3Z_J3eRKUA2eZMTqdJyW2Wwtc_c',
    appId: '1:123249181420:ios:3918557103fb1158255bc9',
    messagingSenderId: '123249181420',
    projectId: 'flutterai-d8cd5',
    storageBucket: 'flutterai-d8cd5.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7jhdmQ6bfG1eeKjRqZ2vC0uY1QqbbcNA',
    appId: '1:123249181420:web:db22d11ca5ca5de0255bc9',
    messagingSenderId: '123249181420',
    projectId: 'flutterai-d8cd5',
    authDomain: 'flutterai-d8cd5.firebaseapp.com',
    storageBucket: 'flutterai-d8cd5.firebasestorage.app',
    measurementId: 'G-2J8M10JGTM',
  );

}